Plugin('RTx::ExtJS4');
Plugin('RTx::UpdateHistory');
Plugin('RTx::HistoryComponent');
Plugin('RT::Extension::UserSearch');
Plugin('RT::Extension::ExtractCustomFieldValues');
Plugin('RTx::AddServiceData');
Plugin('RT::Action::ChangeOwner');
Plugin('RT::Action::SetOwner');
Plugin('RTx::Action::SubjectAndEvent');
