base:
  build: .
  dockerfile: docker/base/Dockerfile
library:
  build: .
  dockerfile: docker/library/Dockerfile
  extends:
    service: base
source:
  build: .
  dockerfile: docker/source/Dockerfile
  extends:
    service: library
runtime:
  build: .
  dockerfile: docker/runtime/Dockerfile
  extends:
    service: source