base:
  build: .
  dockerfile: docker/base/Dockerfile
library:
  build: .
  dockerfile: docker/library/Dockerfile
source:
  build: .
  dockerfile: docker/source/Dockerfile
runtime:
  build: .
  dockerfile: docker/runtime/Dockerfile
netways:
  build: .
  dockerfile: docker/netways/Dockerfile
  container_name: rt4netways
  ports:
    - 80
    - 443
    - 25
  privileged: true
  restart: always
  extends:
    service: runtime
icinga:
  build: .
  dockerfile: docker/icinga/Dockerfile
  container_name: rt4icinga
  ports:
    - 80
    - 443
    - 25
  privileged: true
  restart: always
  extends:
    service: runtime
