---
abstract: 'RT-Extension-QueueCategories Extension'
author:
  - 'NETWAYS GmbH L<support@netways.de|mailto:support@netways.de>'
build_requires:
  ExtUtils::MakeMaker: '6.59'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Module::Install version 1.19, CPAN::Meta::Converter version 2.150005'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: RT-Extension-QueueCategories
no_index:
  directory:
    - inc
requires:
  perl: '5.010001'
resources:
  license: http://opensource.org/licenses/gpl-license.php
  repository: https://github.com/NETWAYS/rt-extension-queuecategories
version: 2.1.0
x_module_install_rtx_version: '0.40'
x_requires_rt: 4.4.2
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
