Set($MessageBoxIncludeSignature, undef);
Set($MessageBoxIncludeSignatureOnComment, undef);
Set($MessageBoxRichText, undef);
Set($TrustHTMLAttachments, 1);
Set($OldestTransactionsFirst, 0);
Set($MaxAttachmentSize, 25_000_000);
Set($MaxInlineBody, 8000000);
Set($SuppressInlineTextFiles, 1);
Set($ParseNewMessageForTicketCcs, 1);
Set($ShowHistory, 'delay');
Set($RedistributeAutoGeneratedMessages, "privileged");
Set($UsernameFormat, "verbose");
Set(%FullTextSearch,
   Enable  => 1,
   Indexed => 0,
);
